<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;


    protected $guarded = [];

    const DEPARTMENT_TEKNIK_SIPIL = "Jurusan Teknik Sipil";
    const DEPARTMENT_TEKNIK_MESIN = "Jurusan Tenik Mesin ";
    const DEPARTMENT_TEKNIK_ELEKTRO = "Jurusan Teknik Elektro";
    const DEPARTMENT_TEKNIK_KIMIA = "Jurusan Teknik Kimia";
    const DEPARTMENT_AKUNTANSI = "Jurusan Akuntansi";
    const DEPARTMENT_ADMINISTRASI_BISNIS = "Jurusan Teknik Administrasi Bisnis";
    const DEPARTMENT_TEKNIK_KOMPUTER = "Jurusan Teknik Komputer";
    const DEPARTMENT_MANAJEMEN_INFORMATIKA = "Jurusan Manajemen Informatika";
    const DEPARTMENT_BAHASA_INGGRIS = "Jurusan Bahasa Inggris";

    const DEPARTMENT_CHOICE = [
        self::DEPARTMENT_TEKNIK_SIPIL => self::DEPARTMENT_TEKNIK_SIPIL,
        self::DEPARTMENT_TEKNIK_MESIN => self::DEPARTMENT_TEKNIK_MESIN,
        self::DEPARTMENT_TEKNIK_ELEKTRO => self::DEPARTMENT_TEKNIK_ELEKTRO,
        self::DEPARTMENT_TEKNIK_KIMIA => self::DEPARTMENT_TEKNIK_KIMIA,
        self::DEPARTMENT_AKUNTANSI => self::DEPARTMENT_AKUNTANSI,
        self::DEPARTMENT_ADMINISTRASI_BISNIS => self::DEPARTMENT_ADMINISTRASI_BISNIS,
        self::DEPARTMENT_TEKNIK_KOMPUTER => self::DEPARTMENT_TEKNIK_KOMPUTER,
        self::DEPARTMENT_MANAJEMEN_INFORMATIKA => self::DEPARTMENT_MANAJEMEN_INFORMATIKA,
        self::DEPARTMENT_BAHASA_INGGRIS => self::DEPARTMENT_BAHASA_INGGRIS,
    ];

    const STUDY_PROGRAM_D3_TEKNIK_SIPIL = "D3 Teknik Sipil";
    const STUDY_PROGRAM_D4_PERANCANGAN_JALAN_DAN_JEMBATAN = "D4 Perancangan Jalan dan Jembatan";
    const STUDY_PROGRAM_D4_TEKNOLOGI_PRODUKSI_TANAMAN_PERKEBUNAN = "D4 Teknologi  Produksi Tanaman Perkebunan";
    const STUDY_PROGRAM_D3_TEKNIK_MESIN = "D3 Teknik Mesin";
    const STUDY_PROGRAM_D4_TEKNIK_MESIN_PRODUKSI_DAN_PERAWATAN = "D4 Teknik Mesin Produksi dan Perawatan";
    const STUDY_PROGRAM_D3_TEKNIK_LISTRIK = "D3 Teknik Listrik";
    const STUDY_PROGRAM_D3_TEKNIK_ELEKTRONIKA = "D3 Teknik Elektronika";
    const STUDY_PROGRAM_D3_TEKNIK_TELEKOMUNIKASI = "D3 Teknik Telekomunikasi";
    const STUDY_PROGRAM_D4_TEKNIK_TELEKOMUNIKASI = "D4 Teknik Telekomunikasi";
    const STUDY_PROGRAM_D4_TEKNIK_ELEKTRO = "D4 Teknik Elektro";
    const STUDY_PROGRAM_D3_TEKNIK_KIMIA = "D3 Teknik Kimia";
    const STUDY_PROGRAM_D3_TEKNOLOGI_PANGAN = "D3 Teknologi Pangan";
    const STUDY_PROGRAM_D4_TEKNOLOGI_KIMIA_INDUSTRI = "D4 Teknologi Kimia Industri";
    const STUDY_PROGRAM_D4_TEKNIK_ENERGI = "D4 Teknik Energi";
    const STUDY_PROGRAM_S2_TEKNIK_ENERGI_TERBARUKAN = "S2 Teknik Energi Terbarukan";
    const STUDY_PROGRAM_D3_AKUNTANSI = "D3 Akuntansi";
    const STUDY_PROGRAM_D4_AKUTANSI_SEKTOR_PUBLIK = "D4 Akuntansi Sektor Publik";
    const STUDY_PROGRAM_D3_ADMINISTRASI_BISNIS = "D3 Administrasi Bisnis";
    const STUDY_PROGRAM_D4_MANAJEMEN_BISNIS = "D4 Manajemen Bisnis";
    const STUDY_PROGRAM_D4_USAHA_PERJALANAN_WISATA = "D4 Usaha Perjalanan Wisata";
    const STUDY_PROGRAM_D3_TEKNIK_KOMPUTER = "D3 Teknik Komputer";
    const STUDY_PROGRAM_D4_TEKNOLOGI_INFORMATIKA_MULTIMEDIA_DIGITAL = "D4 Teknologi Informatika Multimedia Digital";
    const STUDY_PROGRAM_D3_MANAJEMEN_INFORMATIKA = "D3 Manajemen Informatika";
    const STUDY_PROGRAM_D4_MANAJEMEN_INFORMATIKA = "D4 Manajemen Informatika";
    const STUDY_PROGRAM_D3_BAHASA_INGGRIS = "D3 Bahasa Inggris";



    const STUDY_PROGRAM_CHOICE = [
        self::STUDY_PROGRAM_D3_TEKNIK_SIPIL => self::STUDY_PROGRAM_D3_TEKNIK_SIPIL,
        self::STUDY_PROGRAM_D4_PERANCANGAN_JALAN_DAN_JEMBATAN => self::STUDY_PROGRAM_D4_PERANCANGAN_JALAN_DAN_JEMBATAN,
        self::STUDY_PROGRAM_D4_TEKNOLOGI_PRODUKSI_TANAMAN_PERKEBUNAN => self::STUDY_PROGRAM_D4_TEKNOLOGI_PRODUKSI_TANAMAN_PERKEBUNAN,
        self::STUDY_PROGRAM_D3_TEKNIK_MESIN => self::STUDY_PROGRAM_D3_TEKNIK_MESIN,
        self::STUDY_PROGRAM_D4_TEKNIK_MESIN_PRODUKSI_DAN_PERAWATAN => self::STUDY_PROGRAM_D4_TEKNIK_MESIN_PRODUKSI_DAN_PERAWATAN,
        self::STUDY_PROGRAM_D3_TEKNIK_LISTRIK => self::STUDY_PROGRAM_D3_TEKNIK_LISTRIK,
        self::STUDY_PROGRAM_D3_TEKNIK_ELEKTRONIKA => self::STUDY_PROGRAM_D3_TEKNIK_ELEKTRONIKA,
        self::STUDY_PROGRAM_D3_TEKNIK_TELEKOMUNIKASI => self::STUDY_PROGRAM_D3_TEKNIK_TELEKOMUNIKASI,
        self::STUDY_PROGRAM_D4_TEKNIK_TELEKOMUNIKASI => self::STUDY_PROGRAM_D4_TEKNIK_TELEKOMUNIKASI,
        self::STUDY_PROGRAM_D4_TEKNIK_ELEKTRO => self::STUDY_PROGRAM_D4_TEKNIK_ELEKTRO,
        self::STUDY_PROGRAM_D3_TEKNIK_KIMIA => self::STUDY_PROGRAM_D3_TEKNIK_KIMIA,
        self::STUDY_PROGRAM_D3_TEKNOLOGI_PANGAN => self::STUDY_PROGRAM_D3_TEKNOLOGI_PANGAN,
        self::STUDY_PROGRAM_D4_TEKNOLOGI_KIMIA_INDUSTRI => self::STUDY_PROGRAM_D4_TEKNOLOGI_KIMIA_INDUSTRI,
        self::STUDY_PROGRAM_D4_TEKNIK_ENERGI => self::STUDY_PROGRAM_D4_TEKNIK_ENERGI,
        self::STUDY_PROGRAM_S2_TEKNIK_ENERGI_TERBARUKAN => self::STUDY_PROGRAM_S2_TEKNIK_ENERGI_TERBARUKAN,
        self::STUDY_PROGRAM_D3_AKUNTANSI => self::STUDY_PROGRAM_D3_AKUNTANSI,
        self::STUDY_PROGRAM_D4_AKUTANSI_SEKTOR_PUBLIK => self::STUDY_PROGRAM_D4_AKUTANSI_SEKTOR_PUBLIK,
        self::STUDY_PROGRAM_D3_ADMINISTRASI_BISNIS => self::STUDY_PROGRAM_D3_ADMINISTRASI_BISNIS,
        self::STUDY_PROGRAM_D4_MANAJEMEN_BISNIS => self::STUDY_PROGRAM_D4_MANAJEMEN_BISNIS,
        self::STUDY_PROGRAM_D4_USAHA_PERJALANAN_WISATA => self::STUDY_PROGRAM_D4_USAHA_PERJALANAN_WISATA,
        self::STUDY_PROGRAM_D3_TEKNIK_KOMPUTER => self::STUDY_PROGRAM_D3_TEKNIK_KOMPUTER,
        self::STUDY_PROGRAM_D4_TEKNOLOGI_INFORMATIKA_MULTIMEDIA_DIGITAL => self::STUDY_PROGRAM_D4_TEKNOLOGI_INFORMATIKA_MULTIMEDIA_DIGITAL,
        self::STUDY_PROGRAM_D3_MANAJEMEN_INFORMATIKA => self::STUDY_PROGRAM_D3_MANAJEMEN_INFORMATIKA,
        self::STUDY_PROGRAM_D4_MANAJEMEN_INFORMATIKA => self::STUDY_PROGRAM_D4_MANAJEMEN_INFORMATIKA,
        self::STUDY_PROGRAM_D3_BAHASA_INGGRIS => self::STUDY_PROGRAM_D3_BAHASA_INGGRIS,
    ];

    const DEGREE_D3 = "Diploma 3";
    const DEGREE_D4 = "Diploma 4";
    const DEGREE_S2 = "Strata 2";
    const DEGREE_MSU = "MSU";

    const DEGREE_CHOICE = [
        self::DEGREE_D3 => self::DEGREE_D3,
        self::DEGREE_D4 => self::DEGREE_D4,
        self::DEGREE_S2 => self::DEGREE_S2,
        self::DEGREE_MSU => self::DEGREE_MSU,
    ];
}
